### ISSUE TITLE
Los archivos del módulo deberían estar en la raíz del proyecto

### ISSUE THREAD

**Issue by mrsarm** [odoo-l10n-ar/l10n_ar_states#3]
Considerar esto como un bug es relativo, pero la convención de la mayoría de los módulos es poner los archivos del módulo en la raiz del proyecto, para luego poder hacer checkout en una carpeta de addons y poder usar el módulo directamente desde el checkout.

De la manera que está ahora obliga a hacer una working copy al directorio de addons luego del checkout, o agregar todo el checkout como un directorio de addons solo por este módulo.

Además, viendo los demás repositorios del proyecto, la manera de organizar los archivos que indico es la que se observa en los demás módulos.

**Comment by csrocha** [comment]
@mrsarm , es un issue repetido, por favor continua la discusión en odoo-l10n-ar/odoo-l10n-ar.github.io#7
